name: EKS Deployment Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**' # Triggers only when these files change
      - '.github/workflows/deploy.yml' # Trigger if this file changes
  pull_request:
    branches:
      - main

env:
  AWS_REGION: us-west-2
  EKS_CLUSTER_NAME: hello-world-cluster

jobs:
  terraform:
    name: Terraform Provisioning
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }} && github.event.paths.any == 'terraform/**'

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Initialize Terraform
      run: terraform init

    - name: Apply Terraform
      run: terraform apply -auto-approve

    - name: Output kubeconfig
      uses: actions/upload-artifact@v3
      with:
        name: kubeconfig
        path: kubeconfig

  helm:
    name: Helm Deployment
    runs-on: ubuntu-latest
    needs: terraform

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Helm
      uses: azure/setup-helm@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Download kubeconfig artifact
      uses: actions/download-artifact@v3
      with:
        name: kubeconfig

    - name: Export kubeconfig
      run: |
        mkdir -p ~/.kube
        cp ./kubeconfig ~/.kube/config

    - name: Helm Install
      run: |
        helm upgrade --install hello-world-release ./helloworld --wait
